name: pixabay
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: ---
repository : ---
author: Ken <kenomaru@hotmail.it>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
